### ISSUE TITLE
Add Links to sample.json

### ISSUE THREAD

**Issue by dhcgn** [dhcgn/workplace-sync#30]
Add these links to https://github.com/dhcgn/workplace-sync/blob/main/sample.json

- [x] Total Command _as Installer_ https://totalcommander.ch/win/tcmd1052x64.exe change file name to _tcmd.exe_ 
- [x] oxipng https://github.com/shssoichiro/oxipng/releases
- [x] rage https://github.com/str4d/rage/releases/download/v0.9.0/rage-v0.9.0-x86_64-windows.zip _decompress flat_
- [x] darktable https://www.darktable.org/install/ with _skipped_

**Comment by clairecharles** [comment]
hey, in what files should i add these links?

**Comment by dhcgn** [comment]
The description was incomplete, this has now been expanded to allow easy implementation by third parties.
